bytedance: mm: fixed a PAGEFLAG_FALSE compile error
The compilation log is as follows:
./include/linux/page-flags.h:538:54: error:
 macro "PAGEFLAG_FALSE" passed 2 arguments, but takes just 1
 PAGEFLAG_FALSE(VmemmapSelfHosted, vmemmap_self_hosted)
                                                      ^
./include/linux/page-flags.h:538:15: error: expected ‘;’ before ‘static’
 PAGEFLAG_FALSE(VmemmapSelfHosted, vmemmap_self_hosted)
               ^
The commit 85da352a871d ("mm: memory_hotplug: make hugetlb_optimize_vmemmap
compatible with memmap_on_memory") backported from commit 66361095129b
upstream.

Before there is no folio related patch, PAGEFLAG_FALSE() has only
one input parameter.

Signed-off-by: Yunhui Cui <cuiyunhui@bytedance.com>