selftests/sgx: Ignore OpenSSL 3.0 deprecated functions warning
commit 5f4d1fd5b5d3506759b5d9cf20bb5fb5b8bdcab1 upstream.

OpenSSL 3.0 deprecates some of the functions used in the SGX
selftests, causing build errors on new distros. For now ignore
the warnings until support for the functions is no longer
available and mark FIXME so that it can be clear this should
be removed at some point.

Intel-SIG: commit 5f4d1fd5b5d3 selftests/sgx: Ignore OpenSSL 3.0
deprecated functions warning.
Backport the fix for build errors as below on lkp:

> sigstruct.c:120:17: error: 'ERR_get_error_line' is deprecated:
> Since OpenSSL 3.0 [-Werror=deprecated-declarations]

Signed-off-by: Kristen Carlson Accardi <kristen@linux.intel.com>
Reviewed-by: Jarkko Sakkinen <jarkko@kernel.org>
Signed-off-by: Shuah Khan <skhan@linuxfoundation.org>
Reported-by: kernel test robot <lkp@intel.com>
[ Zhiquan: amend commit log. ]
Signed-off-by: Zhiquan Li <zhiquan1.li@intel.com>
Signed-off-by: Jiawei Gu <gujiawei.will@bytedance.com>