bytedance:netkit: fix missing rtnl_nla_parse_ifla function
After cherry-pick LTS commit <ace1b0ae3097> (net: validate veth and vxcan peer ifindexes),
we found a compile error with the following message:
drivers/net/netkit.c: 335:10: error: implicit declaration of function
'rtnl_nla_parse_ifla '; did you mean 'rtnl_nla_parse_ifinfomsg'?

After analysis, the rtnl_nla_parse_ifla has been replaced with
rtnl_nla_parse_ifinfomsg, and the netkit code needs to be adapted

Signed-off-by: Rui Qi <qirui.001@bytedance.com>